### ISSUE TITLE
dry run output of eessi-dynamic should be a bit more verbose

### ISSUE THREAD

**Issue by boegel** [EESSI/infrastructure#32]
Example:

```
[boegel@login ~]$ eessi-dynamic --create-node c5.24xlarge --node-name c5-24xlarge-gromacs-test --node-description "test node for GROMACS AWS benchmarks" --node-issuer boegel --node-user-name boegel --dry-run
Creating 'c5-24xlarge-gromacs-test'.
[boegel@login ~]$
```

Nothing in the output makes it's clear it's a dry run, and I was expecting additional output that somehow shows that the expected result would be achieved.

**Comment by terjekv** [comment]
This is partially supported now, but is now uselessly verbose (thank you terraform).
