### ISSUE TITLE
set up jump host witn Ansible installed

### ISSUE THREAD

**Issue by boegel** [EESSI/infrastructure#4]
So we can easily run playbooks on instances without having to install anything ourselves locally.

**Comment by terjekv** [comment]
Login node / jump host generated via terraform: https://github.com/EESSI/infrastructure/tree/main/static/terraform
This needs to be updated to use our packer-generated AMI from https://github.com/EESSI/infrastructure/commit/bba2af693e2e8576b579e78a94e65465c43d5263 to ensure users and such are generated correctly.

**Comment by terjekv** [comment]
Now using our AMIs: https://github.com/EESSI/infrastructure/commit/2638c1ca60b8784062541cad5b345e5c528db06a
