### ISSUE TITLE
set up AMIs for build nodes

### ISSUE THREAD

**Issue by boegel** [EESSI/infrastructure#5]
Should definitely include Singularity, perhaps other stuff.

Also access control, which SSH keys can get access?

**Comment by terjekv** [comment]
I'm looking at this now. I'm thinking we should provide a default EESSI account that has the ssh keys for admins, in addition to the default user that the provisioner creates. The images are likely going to be based on RHEL8.

**Comment by terjekv** [comment]
A first pass, using packer: https://github.com/EESSI/infrastructure/commit/bba2af693e2e8576b579e78a94e65465c43d5263

**Comment by terjekv** [comment]
Probably closed via https://github.com/EESSI/infrastructure/commit/a7c69f4e9e429470ced0de8d841e9e910546c47a
