### ISSUE TITLE
system-wide eessi-upload-to-staging script on login.eessi-hpc.org is not latest version

### ISSUE THREAD

**Issue by boegel** [EESSI/infrastructure#55]
The script at `/usr/local/eessi/eessi-upload-to-staging` doesn't upload a metadata file (cfr. https://github.com/EESSI/infrastructure/pull/49)

**Comment by boegel** [comment]
@terjekv I guess this is just an oversight?

**Comment by terjekv** [comment]
Uhm, yes.

**Comment by terjekv** [comment]
Fixed by adding a cronjob that updates the upload script hourly. We should probably add that to the images. Nodes get the latest version upon creation, which usually hasn't been a big deal, but login and similar nodes live forever.

The script is dead simple:

```
[root@login ~]# cat /etc/cron.hourly/update-upload-script
#!/bin/sh

DEST=/usr/local/eessi/eessi-upload-to-staging
SOURCE=https://raw.githubusercontent.com/eessi/infrastructure/main/eessi-upload-to-staging
curl --silent $SOURCE --output $DEST
chmod a+rx $DEST
```
