### ISSUE TITLE
Delegate a subdomain to Route53? 

### ISSUE THREAD

**Issue by terjekv** [EESSI/infrastructure#8]
To ensure functional DNS for the terraformed instances, should/could we delegate a subdomain to Route53? https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/CreatingNewSubdomain.html

This would allow for infrastructure hosts on AWS to get a proper DNS name via route53. I’d suggest maybe infra.eessi-hpc.org? We could then also CNAME login.eessi-hpc.org to login.infra.eessi-hpc.org.

This would allow for recreation of the login server with a new IP and whatnot without needing to make (manual) changes to the current DNS setup.

**Comment by boegel** [comment]
@terjekv The subdomain should be AWS specific, so `aws` should be in there imho. `aws.eessi-hpc.org`?

**Comment by terjekv** [comment]
There is nothing AWS-tied to the DNS itself if you use Route53. You can use their api to point to a DNS name to an IP in google cloud if you like.

**Comment by boegel** [comment]
@JvD007 We'll need your help for this...

**Comment by terjekv** [comment]
@JvD007 Help? :)

**Comment by terjekv** [comment]
We now have eessi-infra.org for this use. Name standards need to be documented.
